#!/usr/bin/env bash
# This script configures localhost and facebook.com IP resolution

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
