#!/usr/bin/env bash
# This script configures localhost and facebook.com IP resolution

sed -i '/localhost/s/127.0.0.1/127.0.0.2/' /etc/hosts
sed -i '/facebook/d' /etc/hosts

echo "8.8.8.8 facebook.com" >> /etc/hosts
